# Generated by Django 4.1.2 on 2022-10-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_versetiming_verse_versetiming_verse_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='end_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='start_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
