# Generated by Django 4.1.3 on 2023-05-04 00:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_chapter_end_page_remove_chapter_start_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["number"]},
        ),
        migrations.AlterModelOptions(
            name="verse",
            options={"ordering": ["number"]},
        ),
        migrations.AlterField(
            model_name="author",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.upload_author
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="tariha",
            field=models.CharField(
                choices=[
                    ("tidjan", "Tidjan"),
                    ("mouride", "Mouride"),
                    ("niassene", "Niassene"),
                    ("layenne", "Layene"),
                    ("khadre", "Khadre"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="xassida",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
