# Generated by Django 4.1.3 on 2023-07-31 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_word_options_alter_xassida_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verse",
            old_name="transcripiton",
            new_name="transcription",
        ),
    ]
