# Generated by Django 4.1.3 on 2023-08-20 09:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_xassida_options_reciter_tariha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="file",
            field=models.FileField(upload_to=api.models.upload_audio),
        ),
    ]
