# Generated by Django 4.1.3 on 2023-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_audio_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audio",
            options={"ordering": ["reciter"]},
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["slug"]},
        ),
        migrations.AlterField(
            model_name="audio",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
