# Generated by Django 4.1.3 on 2023-08-24 22:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_audio_options_alter_author_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audio",
            options={"ordering": ["reciter__name"]},
        ),
        migrations.AlterModelOptions(
            name="reciter",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="reciter",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.upload_reciter
            ),
        ),
    ]
