# Generated by Django 4.1.3 on 2023-08-28 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_audio_options_alter_reciter_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="audio",
            unique_together={("xassida", "reciter")},
        ),
    ]
